apiVersion: v1
kind: Pod
metadata:
  name: piflow 
spec:
  containers:
  - name: master 
    image: registry.cn-hangzhou.aliyuncs.com/cnic_piflow/piflow:v0.9.1
    command: ["/bin/bash","-c","--"]
    args: ["while true; do sleep 30; done;"]
    env:
    - name: HOST_IP
      valueFrom: 
        fieldRef: 
         fieldPath: status.podIP
    ports:
    - name: front
      containerPort: 6001
      hostPort: 6001 
      protocol: TCP
    - name: web
      containerPort: 6002 
      hostPort: 6002
      protocol: TCP
